### ISSUE TITLE
Update to use zIndex

### ISSUE THREAD

**Issue by dhrrgn** [bodyflex/react-native-simple-modal#14]
As of React Native 0.30.0, the `zIndex` style prop is supported.  The library should take advantage of this.  Setting it to something high by default (e.g. `10000`) on the `container` style should work, then if need-be the developer can override this in the `containerStyle`.  I would submit a PR to add this, but I don't have time at the moment.

**Comment by idajimenez** [comment]
I am also using RN 0.30 and when I use the modal together with a <View> that has a elevation props, the view is not covered by the modal.

**Comment by httnn** [comment]
I've also experienced some z-index issues on Android so not quite confident about the stability of z-indexes on RN right now...

although I do see the advantage that z-indexes would bring (making the use of this component slightly easier), using z-indexes would gear people towards using several modals per app, one in every component that uses a one, which will have an effect on performance. a global modal component at the root level that is controlled by something like redux seems much more sensible imo.

**Comment by naman03malhotra** [comment]
@dhrrgn any progress on this?
