### ISSUE TITLE
Display model contents without animation.

### ISSUE THREAD

**Issue by joshiSumant** [bodyflex/react-native-simple-modal#15]
Hi, I have tried 

```
animationDuration={0}
animationTension={0}
```

When trying to use Model. But we I have tried, view is getting displayed as animation way in fade way.  As per [https://facebook.github.io/react-native/docs/modal.html], animationType is deprecated. Are we having any other way to display view without animation.

**Comment by httnn** [comment]
not right now, but feel free to submit a PR!

**Comment by Nadeermalangadan** [comment]
#19

**Comment by httnn** [comment]
this is now in version 5.0.0, cc @joshiSumant
