### ISSUE TITLE
Remove  event listener for hardwareBackPress on component unmount

### ISSUE THREAD

**Issue by alekseykarpenko** [bodyflex/react-native-simple-modal#21]
When Modal dialog is unmounted, event listener for Android hardware back button press (```hardwareBackPress```) is still there. This leads to problems in multi-page applications and/or when using other listeners for that event.

So i decided to remove event listener on each ```componentWillUnmount```.

See RN #20

**Comment by httnn** [comment]
thanks for the PR @alekseykarpenko, and sorry for the delay. will check it out this week.

**Comment by httnn** [comment]
this is now in v5.0.0, cc @alekseykarpenko @cenkakin @RyanMan56
