### ISSUE TITLE
disableOnBackPress works until modal unmounted

### ISSUE THREAD

**Issue by cenkakin** [bodyflex/react-native-simple-modal#27]
Hello,
Last implementation of disableOnBackPress is buggy. Sorry, I mislead you. If we add event to backHandler and set disableOnBackPress true, then even if modal is opened or not, back button is not working anymore until modal will be unmounted. So, disableOnBackPress control must be run when only modal is open like my first implementation. Can you check it again?   

Thanks in advance.

**Comment by httnn** [comment]
@cenkakin good point. please submit a pr if you have time!

**Comment by zachrnolan** [comment]
@cenkakin @bodyflex https://github.com/bodyflex/react-native-simple-modal/pull/39

**Comment by httnn** [comment]
@cenkakin @zachrnolan the fix has been merged and released under v8.0.0, thanks guys!
