### ISSUE TITLE
unable to resolve module `expo` from project/main.js

### ISSUE THREAD

**Issue by tolgak87** [bodyflex/react-native-simple-modal#28]
I create a project in EXPO. I run with iOS simulator. App is working. And when I run below command, i got this error:
npm install react-native-simple-modal --save

unable to resolve module `expo` from project/main.js
module does not exist in the module map or in these directories

I checked that almost all my node_modules in project file are gone after run npm install command. I think that`s why I got that error. After that I tried with other modules to install with npm, and result is same.

**Comment by httnn** [comment]
this seems to be a problem with expo and/or npm and unrelated to this library.
