### ISSUE TITLE
Can't use it on my project (undefined is not an object)

### ISSUE THREAD

**Issue by hpbl** [bodyflex/react-native-simple-modal#35]
Hi,

I was trying to use the Modal on my project, but I keep getting this error:
![image](https://user-images.githubusercontent.com/13512825/33216421-8b0fea58-d112-11e7-9597-0cc834d03cb7.png)

These are my dependencies: 
```
  "dependencies": {
    "base-64": "^0.1.0",
    "native-base": "2.1.0",
    "react": "15.4.2",
    "react-native": "0.42.0",
    "react-native-action-button": "^2.7.2",
    "react-native-calendars": "^1.5.8",
    "react-native-device-info": "^0.10.1",
    "react-native-html-render": "^1.0.5",
    "react-native-htmlview": "^0.12.0",
    "react-native-http-cache": "^0.2.0",
    "react-native-keychain": "^1.2.0",
    "react-native-material-textfield": "^0.10.0",
    "react-native-router-flux": "3.38.0",
    "react-native-simple-modal": "^7.0.0",
    "react-native-simple-radio-button": "^2.6.0",
    "react-native-spinkit": "^1.1.1",
    "react-native-swipe-gestures": "^1.0.2",
    "react-native-vector-icons": "~4.0.0",
    "react-redux": "^5.0.3",
    "redux": "^3.6.0",
    "redux-logger": "^2.8.2",
    "redux-promise": "^0.5.3",
    "reselect": "^3.0.1"
  },
```

I am importing modal like this:
`import Modal from 'react-native-simple-modal';`

And using as the example instructed.

Can someone help me with this?

**Comment by hpbl** [comment]
Version 4.0.2 works fine for me.

**Comment by httnn** [comment]
@hpbl I suspect that react-native 0.42 doesn't have [BackHandler](https://facebook.github.io/react-native/docs/backhandler.html) yet. if you can't update react-native, then you're stuck with using 4.x, I'm afraid!
